import type { NextPage } from 'next';
import Head from 'next/head';

import { Header } from '../components/Header';
import { Main } from '../components/Main';
import { Footer } from '../components/Footer';
import { Popup } from '../components/Popup';
import { useAppContext } from '../hooks/useAppContext';

const Home: NextPage = () => {
  const { isOpen } = useAppContext();

  return (
      <div className='bg-gray-800 min-h-screen flex flex-col'>
        <Head>
          <title>Star Wars Heroes</title>
          <meta name='description' content='Generated by create next app'/>
          <link rel='icon' href='/favicon.ico'/>
        </Head>
        {isOpen && <Popup/>}
        <Header/>
        <div className='flex flex-auto'>
          <Main/>
        </div>
        <Footer/>

      </div>
  );
};

export default Home;

